name: Production App Deployment, Docker Hub and Azure

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main

env:
  REGISTRY: ${{ vars.REGISTRY }}
  IMAGE_FRONT_NAME: ${{ vars.IMAGE_FRONT_PRODUCTION_NAME }}
  IMAGE_BACK_NAME: ${{ vars.IMAGE_BACK_PRODUCTION_NAME }}
  IMAGE_FRONT_TAG: ${{ vars.IMAGE_FRONTEND_TAG }}
  IMAGE_BACK_TAG: ${{ vars.IMAGE_BACKEND_TAG }}
  
jobs:
  build_test_publish:
    name: Build, Test, and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and tag frontend Docker image
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_FRONT_TAG }} ./frontend 

      - name: Build and tag backend Docker image
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_BACK_TAG }} ./backend

      - name: Extract tag from ref
        id: extract_tag
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Test the Docker images
        run: docker compose up -d

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend Docker image (latest)
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_FRONT_NAME }}:latest

      - name: Build and push backend Docker image (latest)
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_BACK_NAME }}:latest

      - name: Build and push frontend Docker image (with tag)
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_FRONT_NAME }}:${{ env.TAG_NAME }}

      - name: Build and push backend Docker image (with tag)
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_BACK_NAME }}:${{ env.TAG_NAME }}

  deploy_frontend_to_azure:
    name: Deploy Frontend to Azure
    needs: build_test_publish
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Frontend-Production'
          slot-name: 'Production'
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_FRONT_NAME }}:latest
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND_PRODUCTION }}

  deploy_backend_to_azure:
    name: Deploy Backend to Azure
    needs: build_test_publish
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy Backend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Backend-PRODUCTION'
          slot-name: 'Production'
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_BACK_NAME }}:latest
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND_PRODUCTION }}
