#Build (front),tag (front),Build (Back),tag (Back),test compose with local tag, publish tag (front),publish tag (Back)
name: Build, tag, test and Push Docker Images to DockerHub
on:
  push:
    branches:
      - main
    # tags:
    #   - 'v*.*.*'
env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.event.repository.name }}
  IMAGE_FRONT_NAME: orask/todo-app-frontend
  IMAGE_BACK_NAME: orask/todo-app-backend

jobs:
  build_test_publish:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install docker-compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build, tag frontend Docker image
        run: docker build -t Orask/todo-app/frontend ./frontend 

      - name: Build, tag backend Docker image
        run: docker build -t Orask/todo-app/backend ./backend

      - name: Test the Docker images
        run: docker compose up -d

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: ls
        run: ls -a

      - name: Debug environment variables
        run: echo "Registry ${{ env.REGISTRY }} - Frontend Tag ${{ env.IMAGE_FRONT_NAME }} - Backend Tag ${{ env.IMAGE_BACK_NAME }}"


      - name: Build and push frontend Docker image
        
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_FRONT_NAME }}:latest
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE_FRONT_NAME }}
            org.opencontainers.image.description=Simple Todo application
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Build and push backend Docker image
        
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_BACK_NAME }}:latest
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE_BACK_NAME }}
            org.opencontainers.image.description=Simple Todo application
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
      
